CREATE TABLE IF NOT EXISTS `Categories`(
  `id` CHAR(36) PRIMARY KEY,
  `portfolioId` CHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `type` ENUM('profile','project') NOT NULL,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`portfolioId`) REFERENCES `Portfolios`(id) ON DELETE CASCADE
) 
