CREATE TABLE IF NOT EXISTS `Sections` (
  `id` CHAR(36) PRIMARY KEY,
  `categoryId` CHAR(36) NOT NULL,
  `content` JSON,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`categoryId`) REFERENCES `Categories`(id) ON DELETE CASCADE
  )
